name: CI
on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: npm ci
      - run: npm run build
      - run: npm run format-check
      - run: npm run lint
      - run: npm run test
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
      - uses: actions/upload-artifact@v2
        with:
          name: action.yml
          path: action.yml

  test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [built, committed]
    steps:
      - uses: actions/checkout@v2
      - if: matrix.target == 'built' || github.event_name == 'pull_request'
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - if: matrix.target == 'built' || github.event_name == 'pull_request'
        uses: actions/download-artifact@v2
        with:
          name: action.yml
          path: .

      - name: Test create issue from file
        id: ciff
        uses: ./
        with:
          title: '[CI] test ${{ matrix.target }}'
          content-filepath: ./example-content/output.md
          labels: |
            report
            automated issue
          assignees: peter-evans

      - name: Test update issue from file
        uses: ./
        with:
          issue-number: ${{ steps.ciff.outputs.issue-number }}
          title: '[CI] test ${{ matrix.target }}'
          content-filepath: ./example-content/output.md
          labels: |
            report
            automated issue
          assignees: peter-evans

      - name: Close Issue
        uses: peter-evans/close-issue@v1
        with:
          issue-number: ${{ steps.ciff.outputs.issue-number }}
          comment: '[CI] test ${{ matrix.target }}'

  package:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rm -rf dist
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update distribution
          title: Update distribution
          body: |
            - Updates the distribution for changes on `main`

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-distribution
